spring:
  application:
    name: eureka-server

server:
  port: 10000

eureka:
  client:
    region: sz
    service-url:
      sz-zone1: http://sz-zone1-1:10000/eureka
      sz-zone2: http://sz-zone2-1:10000/eureka
      sz-zone3: http://sz-zone3-1:10000/eureka
---
spring:
  profiles: sz-zone1-1
eureka:
  instance:
    hostname: sz-zone1-node1
  client:
    availability-zones:
      sz: sz-zone1,sz-zone2,sz-zone3
---
spring:
  profiles: sz-zone2-1
eureka:
  instance:
    hostname: sz-zone2-node1
  client:
    availability-zones:
      sz: sz-zone2,sz-zone1,sz-zone3
---
spring:
  profiles: sz-zone3-1
eureka:
  instance:
    hostname: sz-zone3-node1
  client:
    availability-zones:
      sz: sz-zone3,sz-zone1,sz-zone2