spring:
  application:
    name: eureka-server

server:
  port: 10000

eureka:
  server:
    enable-self-preservation: false
  client:
    region: sz
---
spring:
  profiles: sz-zone1-1
eureka:
  instance:
    hostname: sz-zone1-1
  client:
    availability-zones:
      sz: sz-zone1,sz-zone2
    service-url:
      sz-zone1: http://sz-zone1-1:10000/eureka,http://sz-zone1-2:10000/eureka
      sz-zone2: http://sz-zone2-1:10000/eureka
---
spring:
  profiles: sz-zone1-2
eureka:
  instance:
    hostname: sz-zone1-2
  client:
    availability-zones:
      sz: sz-zone1,sz-zone2
    service-url:
      sz-zone1: http://sz-zone1-1:10000/eureka,http://sz-zone1-2:10000/eureka
      sz-zone2: http://sz-zone2-1:10000/eureka
---
spring:
  profiles: sz-zone2-1
eureka:
  instance:
    hostname: sz-zone2-1
  client:
    availability-zones:
      sz: sz-zone2,sz-zone1
    service-url:
      sz-zone1: http://sz-zone1-1:10000/eureka,http://sz-zone1-2:10000/eureka
      sz-zone2: http://sz-zone2-1:10000/eureka